version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: site_teadobem_frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - teadobem_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: site_teadobem_backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - CORS_ORIGINS=*
      - DB_NAME=teadobem
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - teadobem_network

  mongodb:
    image: mongo:latest
    container_name: site_teadobem_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - teadobem_network

networks:
  teadobem_network:
    driver: bridge

volumes:
  mongodb_data:
