services:
  site_institucional:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site_teadobem
    restart: always
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      # Roteia APENAS o domínio 'site.'
      - "traefik.http.routers.site-teadobem.rule=Host(`site.danilobruno.com.br`)"
      - "traefik.http.routers.site-teadobem.entrypoints=websecure"
      - "traefik.http.routers.site-teadobem.tls=true"
      - "traefik.http.routers.site-teadobem.tls.certresolver=mytlschallenge"
      - "traefik.http.services.site-teadobem.loadbalancer.server.port=80"
      - "traefik.docker.network=n8n_default"

networks:
  n8n_default:
    external: true
